### ISSUE TITLE
Pinta.js #1 

### ISSUE THREAD

**Issue by ytzvan** [beerjs/pty#1]
Hola! Gracias por el interés en participar en la primera edición del Pinta.js. Al ser diciembre sabemos que es un mes complicado por el tema de las compras de fin de año y fiestas empresariales, así que trataremos de coordinar un día donde la mayoría pueda participar.
## Fecha

Jueves 18 de Diciembre 
8:30 P.M
## Venue

Brew Stop: http://4sq.com/JPctlV
Via Porras - Ave. 31 Sur.
## Contacto

Ytzvan Mastino 
[Mail](mailto:mastino14@gmail.com)
+507 - 6673-3022

**Comment by alexishevia** [comment]
+1

**Comment by jovib** [comment]
+1
